# -*- coding: utf-8 -*-
"""ML_Project_Phase_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zd_8Qp98tSL_TKKiIIijvwgYSxmBbu1H
"""

!pip install -q -U torch transformers datasets peft bitsandbytes trl accelerate

import torch
import os
from datasets import load_dataset
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from trl import SFTTrainer, SFTConfig
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

# 0. Disable W&B logging
os.environ["WANDB_DISABLED"] = "true"

# 1. Load and Format SQuAD Dataset
print("Loading dataset...")
dataset = load_dataset("squad", split="train[:2000]") # Small slice for demonstration

def format_squad_for_phi3(sample):
    # Standard Phi-3 Instruct format
    return {
        "text": f"<|user|>\nContext: {sample['context']}\n\nQuestion: {sample['question']}<|end|>\n<|assistant|>\n{sample['answers']['text'][0]}<|end|>"
    }

dataset = dataset.map(format_squad_for_phi3)

# 2. Load Model & Tokenizer
model_id = "microsoft/Phi-3.5-mini-instruct"
print(f"Loading {model_id}...")

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16, # Compute in float16 (fast on T4)
    bnb_4bit_use_double_quant=True
)

tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=False,
    torch_dtype=torch.float16 # Request Float16 weights
)

# 3. Prepare for Training
# This casts LayerNorms to float32 for stability
model = prepare_model_for_kbit_training(model)

# 4. Attach LoRA Adapters
peft_config = LoraConfig(
    r=16,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules="all-linear"
)

# 5. Configure Training (T4 STABILITY MODE)
# We disable fp16 to avoid the "Scaler" crash.
training_args = SFTConfig(
    output_dir="./phi3-squad-finetune",
    dataset_text_field="text",
    max_length=512,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    logging_steps=5,
    max_steps=60,
    fp16=False,
    bf16=False,
    optim="paged_adamw_32bit",
    save_strategy="no",
    report_to="none"
)

# 6. Initialize Trainer
trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    args=training_args,
    peft_config=peft_config,
    processing_class=tokenizer
)

# 7. Start Training
print("Starting training (Float32 Optimizer Mode)...")
model.config.use_cache = False
trainer.train()
print("Training finished!")

# 1. Switch model to evaluation mode
model.eval()

# 2. Define a test sample
test_context = "The Apollo program was a human spaceflight program carried out by NASA. It succeeded in landing the first humans on the Moon from 1969 to 1972."
test_question = "When did the Apollo program land humans on the Moon?"

# 3. Format prompt
prompt = f"<|user|>\nContext: {test_context}\n\nQuestion: {test_question}<|end|>\n<|assistant|>"

# 4. Tokenize
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

# 5. Generate Response
print(f"Question: {test_question}")
print("Generating response...")

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=50,
        do_sample=False,
        temperature=0.0
    )

# 6. Decode
response = tokenizer.decode(outputs[0], skip_special_tokens=True)
answer_part = response.split("<|assistant|>")[-1].strip()

print("\n" + "="*30)
print(f"Model Answer:\n{answer_part}")
print("="*30)

from google.colab import drive
import shutil
import os

# --- Step A: Save to a local folder in Colab first ---
local_save_path = "./phi3_squad_final_local"
print(f"1. Saving model adapter files locally to: {local_save_path}")
trainer.save_model(local_save_path)
tokenizer.save_pretrained(local_save_path)
print("   Local save complete.")

# --- Step B: Copy that folder to Google Drive ---
drive.mount('/content/drive')
drive_save_path = "/content/drive/My Drive/ML_Project_Phase2/phi3_squad_final"

print(f"2. Copying files to Google Drive: {drive_save_path}")

if os.path.exists(drive_save_path):
    print("   Existing folder found in Drive. Removing it to ensure fresh copy...")
    shutil.rmtree(drive_save_path)

shutil.copytree(local_save_path, drive_save_path)

print("\nSUCCESS: Full model saved permanently to Google Drive!")