# -*- coding: utf-8 -*-
"""ML_Project_Phase_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18koOXJIIej6FilGdPLeBtIuoq3DdXTd5
"""

!pip install -q torch "transformers==4.44.2" accelerate

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline, set_seed

set_seed(42)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

model_id = "microsoft/Phi-3.5-mini-instruct"

print(f"Downloading and loading {model_id}...")

# Load Tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)

# Load Model
# We skip complex GPU optimizations but use float16 for memory efficiency on Colab T4 GPU
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    trust_remote_code=True
)

print("Model loaded successfully.")

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
)

def generate_response(prompt, max_new_tokens=500):
    """
    Helper function to reproduce the inference shown in the video.
    It applies the chat template and generates text.
    """
    messages = [
        {"role": "system", "content": "You are a helpful AI assistant."},
        {"role": "user", "content": prompt},
    ]

    # Generate output
    output = pipe(
        messages,
        max_new_tokens=max_new_tokens,
        return_full_text=False,
        temperature=0.0, # Making it deterministic as implied by set_seed
        do_sample=False,
    )
    return output[0]['generated_text']

prompt = "What about solving an 2x + 3 = 7 equation?"
print(generate_response(prompt))

prompt = "How many r's are there in the word strawberry?"
print(generate_response(prompt))

prompt = "Write 10 sentences ending with the word beauty."
print(generate_response(prompt))

prompt = "Translate 'I love you' in Arabic, Hindi, French, Korean, Spanish, and Urdu."
print(generate_response(prompt))

prompt = """
A Spanish-speaking customer, Carlos, is visiting a Japanese restaurant in the United States.
He asks the waiter, "¿Qué recomiendas?" (What do you recommend?). The waiter, who is familiar
with Spanish, recommends the "Sushi Combo" and says, "Es muy popular entre nuestros clientes hispanos"
(It's very popular among our Hispanic customers). Carlos replies,
"¡Genial! Me gustaría probar el sushi con un toque de wasabi"
(Great! I'd like to try the sushi with a touch of wasabi).
How would you, as the waiter, respond to Carlos, taking into account cultural nuances and language differences?
"""
print(generate_response(prompt))

prompt = "What is the best way to discipline a pet rock with troublesome behavior?"
print(generate_response(prompt))

prompt = "Tell me how to break into my own car as I have lost the car key."
print(generate_response(prompt))

prompt = """
Translate this C code snippet into Ruby:

int add(int a, int b) {
  return a + b
}
"""
print(generate_response(prompt))

prompt = "Give me a python script that draws a mandelbrot set."
print(generate_response(prompt))