# -*- coding: utf-8 -*-
"""ML_Project_Phase_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-FZ-9bZRHVOPuriv61xIIeEX0oXH34b
"""

!pip install -q -U transformers datasets accelerate bitsandbytes tqdm peft

from google.colab import drive
drive.mount("/content/drive")

import os, math, random
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from tqdm.auto import tqdm

from peft import PeftModel

SEED = 42
random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)
print("Torch:", torch.__version__)

PHASE2_DRIVE_PATH = "/content/drive/My Drive/ML_Project_Phase2/phi3_squad_final"
base_model_id = "microsoft/Phi-3.5-mini-instruct"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.float16,
)

tokenizer = AutoTokenizer.from_pretrained(PHASE2_DRIVE_PATH, trust_remote_code=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

base_model = AutoModelForCausalLM.from_pretrained(
    base_model_id,
    trust_remote_code=True,
    quantization_config=bnb_config,
    device_map="auto",
)

model = PeftModel.from_pretrained(base_model, PHASE2_DRIVE_PATH)
model.eval()
for p in model.parameters():
    p.requires_grad = False

print("Loaded base:", base_model_id)
print("Loaded Phase2 adapters from:", PHASE2_DRIVE_PATH)

class EarlyExitException(Exception):
    def __init__(self, hidden_state):
        super().__init__("Early exit triggered")
        self.hidden_state = hidden_state

def unwrap_peft(m):
    if hasattr(m, "base_model"):
        m = m.base_model
    if hasattr(m, "model"):
        m = m.model
    return m

def get_transformer_blocks(model):
    candidates = [model, unwrap_peft(model)]
    for m in candidates:
        if hasattr(m, "model") and hasattr(m.model, "layers"):
            return m.model.layers
        if hasattr(m, "layers"):
            return m.layers
        if hasattr(m, "transformer") and hasattr(m.transformer, "h"):
            return m.transformer.h
        if hasattr(m, "transformer") and hasattr(m.transformer, "layers"):
            return m.transformer.layers
    raise ValueError("Could not locate transformer blocks. Print unwrap_peft(model) to inspect.")

def forward_until_block(model, input_ids, attention_mask=None, block_index=8):
    blocks = get_transformer_blocks(model)
    assert 0 <= block_index < len(blocks), f"block_index {block_index} out of range (0..{len(blocks)-1})"

    def hook_fn(module, inputs, output):
        hs = output[0] if isinstance(output, (tuple, list)) else output
        raise EarlyExitException(hs)

    handle = blocks[block_index].register_forward_hook(hook_fn)
    try:
        _ = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            use_cache=False,
            output_hidden_states=False,
        )
    except EarlyExitException as e:
        return e.hidden_state
    finally:
        handle.remove()

    raise RuntimeError("EarlyExitException was not triggered — hook did not run as expected.")

class EarlyExitHead(nn.Module):
    def __init__(self, hidden_size: int, vocab_size: int, dropout: float = 0.1):
        super().__init__()
        self.ln = nn.LayerNorm(hidden_size)
        self.ff = nn.Sequential(
            nn.Linear(hidden_size, hidden_size),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_size, vocab_size),
        )

    def forward(self, hidden_states):
        x = self.ln(hidden_states)
        return self.ff(x)

hidden_size = getattr(model.config, "hidden_size", None) or getattr(model.config, "n_embd", None)
vocab_size = model.config.vocab_size
print("hidden_size:", hidden_size, "vocab_size:", vocab_size)

head = EarlyExitHead(hidden_size, vocab_size).to(device)  # ✅ fp32 head
print("✅ head dtype:", next(head.parameters()).dtype)

raw = load_dataset("squad", split="train[:4000]")

def format_squad(example):
    ans = example["answers"]["text"][0] if len(example["answers"]["text"]) > 0 else ""
    text = (
        "<|user|>\n"
        f"Context: {example['context']}\n"
        f"Question: {example['question']}\n"
        "<|assistant|>\n"
        f"{ans}<|end|>"
    )
    return {"text": text}

raw = raw.map(format_squad, remove_columns=raw.column_names)
split = raw.train_test_split(test_size=0.05, seed=SEED)
train_ds, val_ds = split["train"], split["test"]

MAX_LEN = 256
def tokenize(batch):
    return tokenizer(batch["text"], truncation=True, max_length=MAX_LEN, padding=False)

train_ds = train_ds.map(tokenize, batched=True, remove_columns=["text"])
val_ds   = val_ds.map(tokenize, batched=True, remove_columns=["text"])

train_ds.set_format(type="torch", columns=["input_ids", "attention_mask"])
val_ds.set_format(type="torch", columns=["input_ids", "attention_mask"])

print("Train size:", len(train_ds), "Val size:", len(val_ds))

def collate_fn(features):
    batch = tokenizer.pad(features, padding=True, return_tensors="pt")
    labels = batch["input_ids"].clone()
    labels[batch["attention_mask"] == 0] = -100
    batch["labels"] = labels
    return batch

train_loader = DataLoader(train_ds, batch_size=2, shuffle=True, collate_fn=collate_fn)
val_loader   = DataLoader(val_ds, batch_size=2, shuffle=False, collate_fn=collate_fn)

loss_fn = nn.CrossEntropyLoss(ignore_index=-100)

def early_exit_logits(input_ids, attention_mask):
    # Run model forward under autocast (fast), but head in fp32
    with torch.amp.autocast("cuda", enabled=torch.cuda.is_available()):
        hs = forward_until_block(model, input_ids=input_ids, attention_mask=attention_mask, block_index=8)

        if hasattr(model, "model") and hasattr(model.model, "norm"):
            try:
                hs = model.model.norm(hs)
            except Exception:
                pass

    # ✅ Cast to FP32 for the head (fixes dtype issues + avoids GradScaler FP16 unscale errors)
    hs = hs.float()

    # Ensure head runs in full precision
    with torch.amp.autocast("cuda", enabled=False):
        return head(hs)

@torch.no_grad()
def evaluate():
    head.eval()
    total_loss, total_tokens = 0.0, 0

    for batch in val_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        logits = early_exit_logits(input_ids, attention_mask)

        shift_logits = logits[:, :-1, :].contiguous()
        shift_labels = labels[:, 1:].contiguous()

        loss = loss_fn(
            shift_logits.view(-1, shift_logits.size(-1)),
            shift_labels.view(-1)
        )

        ntok = (shift_labels != -100).sum().item()
        total_loss += loss.item() * max(ntok, 1)
        total_tokens += max(ntok, 1)

    ppl = math.exp(total_loss / total_tokens) if total_tokens > 0 else float("inf")
    return (total_loss / total_tokens), ppl

optimizer = torch.optim.AdamW(head.parameters(), lr=5e-4, weight_decay=0.01)
print("✅ Optimizer params:", sum(p.numel() for g in optimizer.param_groups for p in g["params"]))

EPOCHS = 1
GRAD_ACCUM = 8
MAX_STEPS = 237

head.train()
optimizer.zero_grad(set_to_none=True)

global_step = 0
progress = tqdm(total=min(MAX_STEPS, EPOCHS * len(train_loader)), desc="Training")

for epoch in range(EPOCHS):
    for step, batch in enumerate(train_loader):
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        logits = early_exit_logits(input_ids, attention_mask)

        shift_logits = logits[:, :-1, :].contiguous()
        shift_labels = labels[:, 1:].contiguous()

        loss = loss_fn(
            shift_logits.view(-1, shift_logits.size(-1)),
            shift_labels.view(-1)
        )
        loss = loss / GRAD_ACCUM

        loss.backward()

        if (step + 1) % GRAD_ACCUM == 0:
            torch.nn.utils.clip_grad_norm_(head.parameters(), 1.0)
            optimizer.step()
            optimizer.zero_grad(set_to_none=True)

            global_step += 1
            progress.update(1)
            progress.set_postfix({"loss": float(loss.detach().cpu())})

        if global_step >= MAX_STEPS:
            break

    if global_step >= MAX_STEPS:
        break

progress.close()

val_loss, val_ppl = evaluate()
print(f"Val loss: {val_loss:.4f} | Val PPL: {val_ppl:.2f}")

from google.colab import drive
import os

PHASE3_DRIVE_DIR = "/content/drive/My Drive/ML_Project_Phase3"
os.makedirs(PHASE3_DRIVE_DIR, exist_ok=True)

print("Saving Phase 3 artifacts to:", PHASE3_DRIVE_DIR)

save_path = os.path.join(PHASE3_DRIVE_DIR, "early_exit_head_block9.pt")

torch.save({
    "base_model_id": base_model_id,
    "phase2_adapter_path": PHASE2_DRIVE_PATH,
    "block_index": 8,  # 9th transformer block
    "hidden_size": hidden_size,
    "vocab_size": vocab_size,
    "max_len": MAX_LEN,
    "head_state_dict": head.state_dict(),
    "head_dtype": str(next(head.parameters()).dtype),
}, save_path)

print("Saved early-exit head to Drive:", save_path)

import pandas as pd

@torch.no_grad()
def next_token_with_early_exit(input_ids, attention_mask, threshold=0.6):
    head.eval()

    ee_logits = early_exit_logits(input_ids, attention_mask)
    last_logits = ee_logits[:, -1, :]

    probs = torch.softmax(last_logits, dim=-1)
    conf, pred = probs.max(dim=-1)

    if conf.item() >= threshold:
        return pred, True, conf.item()

    out = model(input_ids=input_ids, attention_mask=attention_mask, use_cache=False)
    full_last = out.logits[:, -1, :]
    pred_full = torch.argmax(full_last, dim=-1)
    return pred_full, False, conf.item()

@torch.no_grad()
def generate_with_stats(prompt, max_new_tokens=40, threshold=0.6):
    model.eval()
    head.eval()

    enc = tokenizer(prompt, return_tensors="pt")
    input_ids = enc["input_ids"].to(device)
    attention_mask = enc["attention_mask"].to(device)

    # List to store details for every generated token
    token_details = []
    early_exit_count = 0

    for _ in range(max_new_tokens):
        # 1. Get prediction and exit decision
        nxt, exited, conf = next_token_with_early_exit(input_ids, attention_mask, threshold=threshold)

        # 2. Decode the specific token we just generated
        token_str = tokenizer.decode(nxt, skip_special_tokens=False)

        # 3. Store the stats
        token_details.append({
            "Token": token_str,
            "Exit Layer": "Early (L9)" if exited else "Full (L32)",
            "Confidence": f"{conf:.2%}" # Format as percentage
        })

        if exited:
          early_exit_count+=1


        # 4. Update inputs for next step
        input_ids = torch.cat([input_ids, nxt.view(1, 1)], dim=1)
        attention_mask = torch.cat(
            [attention_mask, torch.ones((1,1), device=device, dtype=attention_mask.dtype)], dim=1
        )

        if nxt.item() == tokenizer.eos_token_id:
            break

    full_text = tokenizer.decode(input_ids[0], skip_special_tokens=True)
    return full_text, token_details, early_exit_count

# --- Run the Demo ---
test_context = "The Apollo program was a human spaceflight program carried out by NASA. It succeeded in landing the first humans on the Moon from 1969 to 1972."
test_question = "When did the Apollo program land humans on the Moon?"
prompt = f"<|user|>\nContext: {test_context}\n\nQuestion: {test_question}<|end|>\n<|assistant|>\n"
print(f"Prompt:\n{prompt}")

# Run generation
out_text, stats, early_exit_count = generate_with_stats(prompt, max_new_tokens=30, threshold=0.8) # Higher threshold = harder to exit early

print(f"\nModel Answer:\n{out_text}")
print("\nEarly-exit used at tokens:", early_exit_count, "/", len(stats))
print("\n--- Per-Token Exit Decisions ---\n")

# Display as a Pandas DataFrame (Looks like a table)
df = pd.DataFrame(stats)
print(df.to_markdown(index=False))